<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Mobile Number_vfb-19</name>
   <tag></tag>
   <elementGuidId>dea37e0e-82c9-4fe6-9928-1fa6b408c675</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#vfb-19</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='vfb-19']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8da7b9d2-9467-46e3-8437-b85bce6f6821</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6b323fb3-dc11-447d-b0e9-877eba7e7d2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>vfb-19</value>
      <webElementGuid>db36046c-a7fa-4cad-ac29-b9596125b312</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>vfb-19</value>
      <webElementGuid>58a877a7-f4ab-4521-a44e-26db544a4602</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vfb-text  vfb-medium   digits </value>
      <webElementGuid>159de8d4-d29c-49e7-977f-d9b755d2c44d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vfb-19&quot;)</value>
      <webElementGuid>6e344d97-81ff-4189-bcdf-7708e72c5940</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='vfb-19']</value>
      <webElementGuid>5e85bb28-f136-4507-9509-3b2e452b8871</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='item-vfb-19']/input</value>
      <webElementGuid>ea8026fd-3434-4c65-8e99-f5c64da21c89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[8]/input</value>
      <webElementGuid>8b923ac0-670d-4164-b1ba-f568aee034c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'vfb-19' and @id = 'vfb-19']</value>
      <webElementGuid>b4bb4961-3b9f-44f6-9370-4926f0c6937f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
