<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__vfb-5</name>
   <tag></tag>
   <elementGuidId>33309a1b-59d1-4739-8313-473901dbb99a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#vfb-5</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='vfb-5']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f8ea3202-829f-4b9f-b805-206617f48a0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>53a13a15-b94f-4757-a575-c535373ae889</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>vfb-5</value>
      <webElementGuid>94c6a5fb-aac1-4483-9b8f-a268252b2138</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>vfb-5</value>
      <webElementGuid>8d675153-9b77-4621-a223-64303d4a2e67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vfb-text  vfb-medium  required  </value>
      <webElementGuid>10595fa2-d60e-4ddf-b126-b3f0c01c5f11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vfb-5&quot;)</value>
      <webElementGuid>e831786b-79aa-4928-90ed-cc33acac0133</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='vfb-5']</value>
      <webElementGuid>ea4d3b18-a771-440a-9906-9d1f0588acfa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='item-vfb-5']/input</value>
      <webElementGuid>6c2dc615-833e-47b6-a45f-5a122a5c0c04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/input</value>
      <webElementGuid>887261b2-729c-49f0-9075-8a7e4511d2a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'vfb-5' and @id = 'vfb-5']</value>
      <webElementGuid>c9267101-b994-4ac9-9375-a06d8e412e89</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
