<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Date of Demo_vfb-18</name>
   <tag></tag>
   <elementGuidId>7e4884b3-fc99-4762-aa56-762c8fcfd813</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#vfb-18</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='vfb-18']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>806f6167-02f6-4e51-8430-41584f01a3ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1b30dff0-7b48-477f-a8fd-d0a070cfee59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>vfb-18</value>
      <webElementGuid>ab01cc66-0e47-4f2f-8482-e3d925bd787b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>vfb-18</value>
      <webElementGuid>7ca4427a-633b-4c65-a23f-cba7644a70ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vfb-text vfb-date-picker vfb-medium hasDatepicker</value>
      <webElementGuid>0d8d2ffd-9604-428b-8c58-4da380de6686</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dp-dateformat</name>
      <type>Main</type>
      <value>mm/dd/yy</value>
      <webElementGuid>6eb5969f-63da-46da-9093-ff159e5f0b5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vfb-18&quot;)</value>
      <webElementGuid>718c948a-9947-461d-afa0-c3a61d7368ac</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='vfb-18']</value>
      <webElementGuid>b26ba4bd-575a-4985-b923-550a89ad248d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='item-vfb-18']/span/input</value>
      <webElementGuid>eb5a55ec-714c-437c-b69c-cd0ab0597773</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[6]/span/input</value>
      <webElementGuid>26756d28-adbf-402f-a9f1-40b7dc1e13aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'vfb-18' and @id = 'vfb-18']</value>
      <webElementGuid>eff2dcfe-b9b6-4736-99d5-fa32033c5b67</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
